### ISSUE TITLE
error with getCommand

### ISSUE THREAD

**Issue by jzy1688** [2amigos/yiiaws#19]
when I try to execute "$s3->getCommand('GetObject',array('Bucket'=>$bucket,'Key'=$key));"
I got an Error :"Argument 2 passed to Guzzle\Service\Client::getCommand() must be an array, string given, called in /Library/WebServer/Documents/protected/extensions/aws/components/A2Base.php on line 85 and defined"

 and  I think it may be some proble with getCommand since I also tried to use getCommand to CreateBucket but got the same error

**Comment by jordigg** [comment]
Same problem here with the test code. The problem is in the A2base.php file.

I have changed line 76 for:

``` php
if($args == false){
    $args = array();
}else{
    $args = current($args);
}
```

$args expect an array value, when is empty throw an error. So when is empty we give them an empty array as a value and everything will be ok.

**Comment by tonydspaniard** [comment]
This issue has been fixed... thanks
