### ISSUE TITLE
Facing Problem with SSL

### ISSUE THREAD

**Issue by dxnabeel** [2amigos/yiiaws#22]
Following is the error I am getting when listing pipelines in ElasticTranscoder

"curl] 60: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"

I am using phar package and running it on local environment with WAMP. Curl version is 7.25.x

I will appreciate any help I can get on this.

**Comment by tonydspaniard** [comment]
Do not use the `phar` file, it is recommended not to use AWS phar file on production. 

It seems that the error you are getting is for a wrong certificate setting.

**Comment by zmilan** [comment]
@dxnabeel there is some additional parameters that u need to set in configuration. Add this:
/**
- Use this options if u get this kind of error
- Error Number: 60. Reason: SSL certificate problem, verify that the CA cert is OK. Details:
- error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed.
- some useful resoruce:
- http://unitstep.net/blog/2009/05/05/using-curl-in-php-to-access-https-ssltls-protected-sites/
  */ 

'ssl.certificate_authority' => true,

/**
- Use this options to send any parameter to curl.
- Options that can be set is listed here:
- http://www.php.net/manual/en/function.curl-setopt.php
  */

'curl.options' => array (
      'CURLOPT_SSL_VERIFYPEER' => false,
      'CURLOPT_SSL_VERIFYHOST' => false,
),

**Comment by dxnabeel** [comment]
@zmilan thanks for the fix. I really appreciate it.
@tonydspaniard thanks for the info. as our application is critical, this will help me make it sure. :)

**Comment by tonydspaniard** [comment]
thanks @zmilan

**Comment by zmilan** [comment]
yw, thanks for this extension and others too :) @tonydspaniard
