### ISSUE TITLE
unable to perform argument passing functions  with custom configuration other than 'default'

### ISSUE THREAD

**Issue by VoBB-Technologies** [2amigos/yiiaws#6]
Hi ,

I was unable to perform  argument passing functions eg:s3->listObjects(array('Bucket'=>'xx')) when using custom prefix , other than 'default_settings' in aws-config.php .

I made minor code modification to the a2base,php -> http://pastebin.com/PTRLCHPi

hope this helps !

**Comment by tonydspaniard** [comment]
@Code-BlUe I have recently fixed the issue. The problem was with the $args at the A2Base, now you can use the default settings as it was. Thanks for your input!

**Comment by tonydspaniard** [comment]
see commit 610d2bc

**Comment by VoBB-Technologies** [comment]
@tonydspaniard  : great  !

it is better if we can use custom prefix in aws-config , as some may have few instance(multiple accounts) for the same service . 

if you can implement http://bit.ly/ZpPgtS , that would be a huge  advantage . I have few instances (like above) ,so still i'm using my own code modification (as i stated above).

**Comment by VoBB-Technologies** [comment]
@tonydspaniard FYI:

I use 'default_settings' (aws-config.php) with your modification , still getting "A2S3 and its behaviors do not have a method or closure named "listObjects"".

with above settings , AWS connection initiate correctly with  AWS SDK , but initiated connection will not return correctly [A2Base.php->line 87 (http://bit.ly/14bs0EE)], thus the error popups .

In my code i return initiated connection immediately (return $command) , with out passing it to parent (CComponent)

side note : other than above I think the error was with A2Base.php->line 87 (http://bit.ly/14bs0EE) =>not returning/initiating the method and arguments correctly
                .

**Comment by tonydspaniard** [comment]
@Code-BlUe A2Base.php->line 87 you are right... fixing it... Thanks Code

Will implement the new configuration settings asap. Please, write an enhancement request. 

BTW with default settings I do work on my current project. I wonder why it doesn't for all.

**Comment by VenuNarukulla** [comment]
Below is the Error in using Composer...
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for 2amigos/yii-aws 1.0.0 -> satisfiable by 2amigos/yii-aws 1.0.0.
    - Can only install one of: 2amigos/yii-aws dev-master, 2amigos/yii-aws 1.0.0.
    - Installation request for 2amigos/yii-aws dev-master -> satisfiable by 2amigos/yii-aws dev-master.

---

<script>
{
    "name": "2amigos/yii-aws",
    "description": "Amazon Web Services SDK PHP 2 Wrapper.",
    "keywords": ["aws", "amazon", "yii"],
    "type": "yii-extension",
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Antonio Ramirez",
            "email": "ramirez.cobos@gmail.com",
            "homepage": "http://www.ramirezcobos.com"
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.phundament.com"
        }
    ],
    "require": {
            "2amigos/yii-aws": "dev-master"
        }
}
</script>

**Comment by tonydspaniard** [comment]
@Venu85 what do you suggest? Versioning? Should I tag versions? Any advice will be highly appreciated

**Comment by VoBB-Technologies** [comment]
@tonydspaniard  : I didn't try this , but yeah , I think versioning is a must  when it comes to composer .

**Comment by tonydspaniard** [comment]
@VoBB-Technologies I have tagged the branch https://github.com/2amigos/yii-aws/tree/v1.0 

You can now reference `"2amigos/yii-aws": "v1.0"` on  your composer file
