### ISSUE TITLE
Enhancement : support custom named services/prefix (in configuration) other than deafult settings

### ISSUE THREAD

**Issue by VoBB-Technologies** [2amigos/yiiaws#7]
hi,

it is better if we can use custom prefix in aws-config , as some may have few instance(multiple accounts) for the same service .

if you can implement http://bit.ly/ZpPgtS , that would be a huge advantage .

**Comment by tonydspaniard** [comment]
What about the following procedure for custom named services? You know that you can also use the library directly right? Yii-aws is a simple wrapper. 

```
use Aws\Ses\SesClient;
use Aws\Common\Enum\Region;

$ses = SesClient::factory(array(
    'key' => Yii::app()->params['aws.ses.key'],
    'secret' => Yii::app()->params['aws.ses.secret'],
    'region' => Region::US_EAST_1
));
```

Nevertheless, I totally agree that provide support custom named services/prefix is something to look at. When I have some free time I may refactor its base class. Ideas?

**Comment by VoBB-Technologies** [comment]
@tonydspaniard : yeah i know  but , I don't like to put yii wrapper connection initialization and another direct initialization (using library directly) and jumble all together .

please follow [https://github.com/2amigos/yii-aws/issues/5#issuecomment-15100616]([https://github.com/2amigos/yii-aws/issues/5#issuecomment-15100616]) for my code modification for custom name prefixes

**Comment by tonydspaniard** [comment]
I have refactored the base class to be able to pass custom configurations (you can use `Yii::app()->params['my.aws.configuration.array']` for this effect.

See #24
